language: node_js
node_js:
    - "0.10"
addons:
    sauce_connect:
        username: "fidian"
        access_key:
            secure: "bFra364AmCO1uTNggVzxUoxFndezd3CpWC4bjlHVvl4jEj5baMsAAQuK3G9pMsyY0QRF8asoskCCE0Wk127kXoqzqXLwT23/DtglmxmUmWXJ/HiDCtWrGAE76LR3g7UFNlzGKZ5Hd8+VbtrQkrX23c8NRKekREACJh/QCZHmETc="
